[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_token_minter = "SPLMint111111111111111111111111111111111111"
milton_test_token = "MILTtest11111111111111111111111111111111111"
token_sales = "SALEprogram111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/path/to/your/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"